# use Java
language: Java

# install junit?
# install mdl for checking Markdown
before_install:
  - gem install mdl
  - jdk_switcher use oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
# need to run junit tests?
script:
  # java checks
  - gradle --version
  - gradle clean check
  - gradle build
  # other linting
  - mdl README.md
