# use Java
language: Java

# install junit?
# install mdl for checking Markdown
before_install:
  - gem install mdl


# ensure the use of the latest version of gradle - much faster to download just the bin
# instead of using a ppa -- travis probably caches this gradle zip folder somewhere.
before_script:
  - wget https://services.gradle.org/distributions/gradle-4.6-bin.zip
  - unzip -d $HOME gradle-4.6-bin.zip
  # probably don't need this but just to be sure
  - rm -rf gradle-4.6-bin.zip
  # add gradle bin to path at the beginning to ensure it overwrites old gradle
  - export PATH="$HOME/gradle-4.6/bin:$PATH"


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
# need to run junit tests?
script:
  # java checks
  - gradle clean
  - gradle build
  # other linting
  - mdl README.md
